<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>False</InvariantGlobalization>
    <UserSecretsId>fb24233c-bf28-4a11-a687-a8959784c22e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CelloPark.Infrastructure\CelloPark.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExportFiles\" />
    <Folder Include="ExceptionFiles\" />
  </ItemGroup>

</Project>
